# Generated by Django 4.2.6 on 2023-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(default=0, verbose_name='Код верификации'),
        ),
    ]
