# Generated by Django 4.2.6 on 2023-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_of_last_modification',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
