# Generated by Django 4.2.6 on 2023-10-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=100, verbose_name='Наименовании версии')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Признак версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('version_number',),
            },
        ),
    ]
